audit_header: false
title:
description:

show_custom_links: true
custom_links:
  - title: Home Purchase Qualifier
    url: http://sgriffin-purchase-site.itclix.com/
  - title: Refinance Rate Checker
    url: http://sgriffin-refinance-site.itclix.com/
  - title: Today's Mortgage Rates
    url: http://sgriffin-rates-site.itclix.com/
  - title: Search Homes
    url: http://sgriffin-find-a-home-site.itclix.com/?xrefresh=1
  - title: Home Valuation
    url: http://sgriffin-home-valuation-address-site.itclix.com/?xrefresh=1
  - title: Apply
    url: http://scottgriffin.com/apply-online/

client:
  name: Scott Griffin
  license_number:
  about_markdown:

  market: Los Angeles
  brand: Scott Griffin Financial
  brokerage:
  address: 11950 Ventura Blvd. Suite 1<br>Studio City, California 91604
  phone: 310-456-4494
  phone_type:
  phone2:
  phone2_type:
  email: scott@scottgriffin.com
  url: http://www.scottgriffin.com
# CTAs:
#   first_CTA_text:
#   first_CTA_URL:
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: Online Loan Application
    CTA_text: >-
      Using our online loan application, you can take your time and complete
      your application whenever it is convenient for you. And, you can always
      save your work and come back and complete it later if you need to.
    CTA_link_text: Apply Now
    CTA_url:
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /uploads/header-logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'

socials:
  review_sm_icons: true
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: 'Los Angeles Mortgage Podcast with Scott Griffin'
  categories:
    - Education
  image: /img/podcast.png
  subtitle:
  description:
  keywords:
  author: 'Scott Griffin'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Los Angeles Mortgage Broker
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#262a82'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 14px
  shadow_color: black
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
